name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  initialize:
    runs-on: ubuntu-latest,
    strategy:
      matrix:
        node-version: [ 20 ]
    steps:
      - uses: actions/checkout@v3

      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: build project
        run: npm run build
#
#      - name: Run linter
#        run: npm run lint
#
#      - name: Run type check
#        run: npm run type:check
#
#      - name: Run i18n check
#        run: npm run i18n:check
#
#      - name: Run unit tests
#        run: npm run test:unit
#
#      - name: Run e2e test
#        run: npm run test:e2e
#
#      - name: Run build storybook
#        run: npm run build:storybook
